@startuml
left to right direction
Title Use Case Diagram
actor Alfonzo
actor Mario
actor Revisor
rectangle PaymentGateway <<actor>>
rectangle "Marios Pizzabar" {
    Alfonzo -- (UC1: Vis menukort)
    Alfonzo -- (UC2: Opret ordre)
    Alfonzo -- (UC3: Vis ordrer)
    Alfonzo -- (UC4: Fjern ordre)
    Mario -- (UC5: Vis statistik)
    Mario -- (UC3: Vis ordrer)
    Revisor -- (UC6: Vis omsætning)
    (UC3: Vis ordrer) -- PaymentGateway


}
@enduml